volumes:
  pg_data:
  static:
  media:
  frontend_static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: markuser4556/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/
    depends_on:
      - db
  frontend:
    image: markuser4556/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static:/frontend_static/
  gateway:
    image: markuser4556/foodgram_gateway
    env_file: .env
    ports:
      - 7070:80
    volumes:
      - static:/static/
      - media:/media/
      - frontend_static:/frontend_static/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend