# Generated by Django 3.2.25 on 2025-10-04 16:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscription',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='prevent_self_subscription',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='subscriber',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'author'), name='unique_subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', django.db.models.expressions.F('author')), _negated=True), name='prevent_self_subscription'),
        ),
    ]
