# Generated by Django 3.2.25 on 2025-10-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Введите единицу измерения', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL', unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
