# Generated by Django 3.2.25 on 2025-10-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
